### ISSUE TITLE
Rendering markdown files ... Error: array_unique() ...

### ISSUE THREAD

**Issue by almaz-free** [yiisoft/yii2-apidoc#198]
### What steps will reproduce the problem?
1. create empty `yii2-docs-generator` directory and enter to it.
2. run `composer require --prefer-dist yiisoft/yii2-apidoc`
3. copy `docs` directory from downloaded github.com/yiisoft/yii2/archive/master.zip archive to project root directory
4. run `vendor/bin/apidoc  guide  docs/guide-ru  ./yii2-offline-guide-ru`

### What's expected?
I don't know, because i trying install yii2-apidoc and compile offline html documentation first time by Installation/Usage guide.

### What do you get instead?
Updating cross references and backlinks... done.
Searching files to process... done.
Rendering markdown files: 0% (0/98) ETA: n/a   Error: array_unique() expects parameter 1 to be array, null given

### Additional info
| Q                  | A
| ------------------ | ---
| Yii vesion         | 2.0.36
| Yii APIDoc version | 2.1.4
| PHP version        | 7.4.7 / 7.4.8
| Operating system   | Windows10 / Debian 10

**Comment by almaz-free** [comment]
I set `YII_DEBUG` to `true` and get this log:
```
Updating cross references and backlinks... done.
Searching files to process... done.
Rendering markdown files: 0% (0/98) ETA: n/a   PHP Warning 'yii\base\ErrorException' with message 'array_unique() expects parameter 1 to be array, null given'

in vendor/yiisoft/yii2-apidoc/helpers/ApiMarkdownTrait.php:38

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError()
#1 vendor/yiisoft/yii2-apidoc/helpers/ApiMarkdownTrait.php(38): array_unique()
#2 vendor/cebe/markdown/Parser.php(345): yii\apidoc\helpers\ApiMarkdown->parseApiLinks()
#3 vendor/cebe/markdown/GithubMarkdown.php(80): cebe\markdown\Parser->parseInline()
#4 vendor/cebe/markdown/Parser.php(186): cebe\markdown\GithubMarkdown->consumeParagraph()
#5 vendor/cebe/markdown/Parser.php(60): cebe\markdown\Parser->parseBlocks()
#6 vendor/yiisoft/yii2-apidoc/helpers/ApiMarkdown.php(62): cebe\markdown\Parser->parse()
#7 vendor/yiisoft/yii2/helpers/BaseMarkdown.php(66): yii\apidoc\helpers\ApiMarkdown->parse()
#8 vendor/yiisoft/yii2-apidoc/helpers/ApiMarkdown.php(175): yii\helpers\BaseMarkdown::process()
#9 vendor/yiisoft/yii2-apidoc/templates/html/GuideRenderer.php(97): yii\apidoc\helpers\ApiMarkdown::process()
#10 vendor/yiisoft/yii2-apidoc/templates/bootstrap/GuideRenderer.php(44): yii\apidoc\templates\html\GuideRenderer->render()
#11 vendor/yiisoft/yii2-apidoc/commands/GuideController.php(96): yii\apidoc\templates\bootstrap\GuideRenderer->render()
#12 [internal function]: yii\apidoc\commands\GuideController->actionIndex()
#13 vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#14 vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams()
#15 vendor/yiisoft/yii2/console/Controller.php(181): yii\base\Controller->runAction()
#16 vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction()
#17 vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction()
#18 vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction()
#19 vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest()
#20 vendor\yiisoft\yii2-apidoc\apidoc(75): yii\base\Application->run()
#21 {main}
```
I make some investigation, and found that `renderingContext` property in ApiMarkdownTrait.php, that used in `array_unique($contexts ...` is always `null`.
