### ISSUE TITLE
Error: Undefined property: stdClass::$methods

### ISSUE THREAD

**Issue by nadar** [yiisoft/yii2-apidoc#37]
Since a few days i get the following error:

````
Error: Undefined property: stdClass::$methods
```

when running (has not changed since):

````
./vendor/bin/apidoc api [comma seperated list of all folders to lookup] /output/folder/ --pageTitle="TITLE" --interactive=0
````

Full process:

```
Searching files to process... done.
Loading apidoc data from cache... no data available.
Checking for updated files... done.
137 files to update.
Processing files... done.
Updating cross references and backlinks... Error: Undefined property: stdClass::$methods
```

any idea?

**Comment by cebe** [comment]
please set YII_DEBUG to true here: https://github.com/yiisoft/yii2-apidoc/blob/master/apidoc#L11 and post the full stack trace of the error.

**Comment by nadar** [comment]
```
Searching files to process... done.
Loading apidoc data from cache... no data available.
Checking for updated files... done.
137 files to update.
Processing files... done.
Updating cross references and backlinks... PHP Warning 'yii\base\ErrorException' with message 'array_merge(): Argument #1 is not an array'

in /Applications/MAMP/htdocs/luya.io/vendor/yiisoft/yii2-apidoc/models/Context.php:187

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'array_merge(): ...', '/Applications/M...', 187, Array)
#1 /Applications/MAMP/htdocs/luya.io/vendor/yiisoft/yii2-apidoc/models/Context.php(187): array_merge(NULL, Array)
#2 /Applications/MAMP/htdocs/luya.io/vendor/yiisoft/yii2-apidoc/models/Context.php(138): yii\apidoc\models\Context->updateSubInterfaceInheritance(Object(stdClass))
#3 /Applications/MAMP/htdocs/luya.io/vendor/yiisoft/yii2-apidoc/components/BaseController.php(148): yii\apidoc\models\Context->updateReferences()
#4 /Applications/MAMP/htdocs/luya.io/vendor/yiisoft/yii2-apidoc/commands/ApiController.php(108): yii\apidoc\components\BaseController->updateContext(Object(yii\apidoc\models\Context))
#5 [internal function]: yii\apidoc\commands\ApiController->actionIndex(Array, 'public_html/api')
#6 /Applications/MAMP/htdocs/luya.io/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#7 /Applications/MAMP/htdocs/luya.io/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\InlineAction->runWithParams(Array)
#8 /Applications/MAMP/htdocs/luya.io/vendor/yiisoft/yii2/console/Controller.php(91): yii\base\Controller->runAction('', Array)
#9 /Applications/MAMP/htdocs/luya.io/vendor/yiisoft/yii2/base/Module.php(455): yii\console\Controller->runAction('', Array)
#10 /Applications/MAMP/htdocs/luya.io/vendor/yiisoft/yii2/console/Application.php(167): yii\base\Module->runAction('api', Array)
#11 /Applications/MAMP/htdocs/luya.io/vendor/yiisoft/yii2/console/Application.php(143): yii\console\Application->runAction('api', Array)
#12 /Applications/MAMP/htdocs/luya.io/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#13 /Applications/MAMP/htdocs/luya.io/vendor/yiisoft/yii2-apidoc/apidoc(53): yii\base\Application->run()
#14 {main}
```

**Comment by cebe** [comment]
Thanks. I have checked in a fix that might solve this. Can you update to latest master and try again?

**Comment by nadar** [comment]
Seems to work again, thanks.
