### ISSUE TITLE
Error: Undefined property: stdClass::$methods

### ISSUE THREAD

**Issue by bigbrush** [yiisoft/yii2-apidoc#57]
Relates to [#37](https://github.com/yiisoft/yii2-apidoc/issues/37)

The problem is i have an interface that extends from 'yii\base\ViewContextInterface'. If it doesn't the error doesn't occur. 

Stack trace:

```
Searching files to process... done.
Loading apidoc data from cache... done.
Checking for updated files... done.
1 file to update.
Processing files... done.(1/1) ETA: n/a
Updating cross references and backlinks... PHP Notice 'yii\base\ErrorException'
with message 'Undefined property: stdClass::$methods'

in C:\wamp\www\big-cms\vendor\yiisoft\yii2-apidoc\models\Context.php:187

Stack trace:
#0 C:\wamp\www\big-cms\vendor\yiisoft\yii2-apidoc\components\BaseController.php(
148): yii\apidoc\models\Context->updateReferences()
#1 C:\wamp\www\big-cms\vendor\yiisoft\yii2-apidoc\commands\ApiController.php(108
): yii\apidoc\components\BaseController->updateContext()
#2 C:\wamp\www\big-cms\vendor\yiisoft\yii2\base\InlineAction.php(55): yii\apidoc
\commands\ApiController->actionIndex()
#3 C:\wamp\www\big-cms\vendor\yiisoft\yii2\base\InlineAction.php(55): ::call_use
r_func_array:{C:\wamp\www\big-cms\vendor\yiisoft\yii2\base\InlineAction.php:55}(
)
#4 C:\wamp\www\big-cms\vendor\yiisoft\yii2\base\Controller.php(154): yii\base\In
lineAction->runWithParams()
#5 C:\wamp\www\big-cms\vendor\yiisoft\yii2\console\Controller.php(108): yii\base
\Controller->runAction()
#6 C:\wamp\www\big-cms\vendor\yiisoft\yii2\base\Module.php(454): yii\console\Con
troller->runAction()
#7 C:\wamp\www\big-cms\vendor\yiisoft\yii2\console\Application.php(167): yii\bas
e\Module->runAction()
#8 C:\wamp\www\big-cms\vendor\yiisoft\yii2\console\Application.php(143): yii\con
sole\Application->runAction()
#9 C:\wamp\www\big-cms\vendor\yiisoft\yii2\base\Application.php(375): yii\consol
e\Application->handleRequest()
#10 C:\wamp\www\big-cms\vendor\yiisoft\yii2-apidoc\apidoc(53): yii\base\Applicat
ion->run()
#11 {main}
```

**Comment by cebe** [comment]
are you using latest master code?

**Comment by bigbrush** [comment]
nope, i'll give it a go asap and give you feedback

**Comment by bigbrush** [comment]
it works with the latest master, so problem already solved. Thanks.
